// GENERATED by scripts/scan-rpcs.ts -- do not edit by hand.
// Re-run with: bun run scan:rpcs
//
// Endpoints are ordered fastest-first by median latency, measured from a single
// machine at generation time. Every one reported the correct chain id, was
// within 30 blocks of the chain head, and returned permissive CORS headers.

export interface GeneratedRpcConfig {
  http: string[];
  /** Every listed endpoint answered a Multicall3 call. */
  multicall: boolean;
  /** Every listed endpoint honoured JSON-RPC batching. */
  batch: boolean;
}

export const GENERATED_RPC_ENDPOINTS: Record<number, GeneratedRpcConfig> = {
  // Ethereum
  1: {
    http: [
      //   35ms
      "https://eth.drpc.org",
      //   52ms, no multicall3, no batch
      "https://ethereum-mainnet.gateway.tatum.io",
      //   56ms
      "https://mainnet.rpc.sentio.xyz",
      //   72ms
      "https://eth1.lava.build",
      //   78ms
      "https://uk.rpc.blxrbdn.com",
    ],
    multicall: false,
    batch: false,
  },
  // Polygon
  137: {
    http: [
      //   42ms, no batch
      "https://polygon-mainnet.g.alchemy.com/v2/demo",
      //   43ms
      "https://polygon.drpc.org",
      //   56ms
      "https://matic.rpc.sentio.xyz",
      //  117ms
      "https://gateway.tenderly.co/public/polygon",
      //  120ms
      "https://public.1rpc.io/matic",
    ],
    multicall: true,
    batch: false,
  },
  // BNB Smart Chain
  56: {
    http: [
      //   99ms
      "https://bsc.rpc.sentio.xyz",
      //  132ms
      "https://rpc-bsc.48.club",
      //  139ms
      "https://56.rpc.thirdweb.com",
      //  148ms
      "https://0.48.club",
      //  149ms
      "https://bsc-rpc.publicnode.com",
    ],
    multicall: true,
    batch: true,
  },
  // Avalanche
  43114: {
    http: [
      //   38ms
      "https://avalanche.drpc.org",
      //   52ms
      "https://api.avax.network/ext/bc/C/rpc",
      //   86ms
      "https://avalanche.rpc.sentio.xyz",
      //  136ms
      "https://avalanche-c-chain-rpc.publicnode.com",
      //  251ms
      "https://avalanche-mainnet.gateway.tenderly.co",
    ],
    multicall: true,
    batch: true,
  },
  // Moonbeam
  1284: {
    http: [
      //   80ms
      "https://moonbeam.drpc.org",
      //  199ms
      "https://public.1rpc.io/glmr",
      //  260ms
      "https://moonbeam.api.onfinality.io/public",
      //  575ms
      "https://moonbeam.api.pocket.network",
      //  641ms
      "https://rpc.swiftnodes.io/rpc/moonbeam",
    ],
    multicall: true,
    batch: true,
  },
  // Evmos
  9001: {
    http: [

    ],
    multicall: false,
    batch: false,
  },
  // Fantom
  250: {
    http: [
      //   77ms
      "https://fantom.drpc.org",
      //  178ms
      "https://public.1rpc.io/ftm",
      //  214ms
      "https://250.rpc.thirdweb.com",
      //  568ms
      "https://fantom.api.pocket.network",
      //  569ms
      "https://rpc2.fantom.network",
    ],
    multicall: true,
    batch: true,
  },
  // Dogechain
  2000: {
    http: [

    ],
    multicall: false,
    batch: false,
  },
  // OKC
  66: {
    http: [
      //  114ms
      "https://oktc.drpc.org",
      //  203ms
      "https://public.1rpc.io/oktc",
      //  524ms
      "https://exchainrpc.okex.org",
    ],
    multicall: true,
    batch: true,
  },
  // EthereumPoW
  10001: {
    http: [
      //   71ms
      "https://mainnet.ethereumpow.org",
    ],
    multicall: true,
    batch: true,
  },
  // Base
  8453: {
    http: [
      //   42ms
      "https://base.drpc.org",
      //   97ms
      "https://base.rpc.sentio.xyz",
      //  122ms
      "https://developer-access-mainnet.base.org",
      //  139ms
      "https://base-rpc.publicnode.com",
      //  141ms
      "https://mainnet.base.org",
    ],
    multicall: true,
    batch: true,
  },
  // PulseChain
  369: {
    http: [
      //   64ms
      "https://rpc.pulsechainstats.com",
      //  100ms
      "https://pulsechain-rpc.publicnode.com",
      //  196ms
      "https://one.valve.city/rpc/vk_demo/evm/369",
      //  220ms
      "https://rpc-pulsechain.g4mm4.io",
      //  228ms
      "https://rpc.pulsechainrpc.com",
    ],
    multicall: true,
    batch: true,
  },
};
