// GENERATED by scripts/scan-rpcs.ts -- do not edit by hand.
// Re-run with: bun run scan:rpcs
//
// Endpoints are ordered fastest-first by median latency, measured from a single
// machine at generation time. Every one reported the correct chain id, was
// within 30 blocks of the chain head, and returned permissive CORS headers.

export interface GeneratedRpcConfig {
  http: string[];
  /** Every listed endpoint answered a Multicall3 call. */
  multicall: boolean;
  /** Every listed endpoint honoured JSON-RPC batching. */
  batch: boolean;
}

export const GENERATED_RPC_ENDPOINTS: Record<number, GeneratedRpcConfig> = {
  // Ethereum
  1: {
    http: [
      //   36ms
      "https://eth.drpc.org",
      //   52ms
      "https://mainnet.rpc.sentio.xyz",
      //   57ms, no multicall3, no batch
      "https://ethereum-mainnet.gateway.tatum.io",
      //   74ms
      "https://uk.rpc.blxrbdn.com",
      //   76ms
      "https://eth1.lava.build",
    ],
    multicall: false,
    batch: false,
  },
  // Polygon
  137: {
    http: [
      //   36ms
      "https://polygon.drpc.org",
      //   49ms
      "https://matic.rpc.sentio.xyz",
      //   98ms
      "https://gateway.tenderly.co/public/polygon",
      //  114ms, no multicall3, no batch
      "https://polygon-mainnet.gateway.tatum.io",
      //  127ms
      "https://polygon-bor-rpc.publicnode.com",
    ],
    multicall: false,
    batch: false,
  },
  // BNB Smart Chain
  56: {
    http: [
      //   78ms
      "https://binance.nodereal.io",
      //   83ms
      "https://bsc-dataseed.bnbchain.org",
      //   92ms
      "https://bsc.rpc.sentio.xyz",
      //  106ms
      "https://bsc-rpc.publicnode.com",
      //  108ms
      "https://bsc-mainnet.public.blastapi.io",
    ],
    multicall: true,
    batch: true,
  },
  // Avalanche
  43114: {
    http: [
      //   35ms
      "https://avalanche.drpc.org",
      //   47ms
      "https://api.avax.network/ext/bc/C/rpc",
      //   52ms
      "https://avalanche.rpc.sentio.xyz",
      //  115ms
      "https://public.1rpc.io/avax/c",
      //  139ms
      "https://avalanche-c-chain-rpc.publicnode.com",
    ],
    multicall: true,
    batch: true,
  },
  // Moonbeam
  1284: {
    http: [
      //  110ms
      "https://moonbeam.drpc.org",
      //  145ms
      "https://public.1rpc.io/glmr",
      //  175ms
      "https://moonbeam.unitedbloc.com",
      //  266ms
      "https://moonbeam.api.onfinality.io/public",
      //  583ms, no multicall3
      "https://moonbeam.api.pocket.network",
    ],
    multicall: false,
    batch: true,
  },
  // Evmos
  9001: {
    http: [

    ],
    multicall: false,
    batch: false,
  },
  // Fantom
  250: {
    http: [
      //   84ms
      "https://fantom.drpc.org",
      //  156ms, no batch
      "https://public.1rpc.io/ftm",
      //  219ms
      "https://250.rpc.thirdweb.com",
      //  562ms
      "https://rpc.fantom.network",
      //  577ms
      "https://fantom.api.pocket.network",
    ],
    multicall: true,
    batch: false,
  },
  // Dogechain
  2000: {
    http: [

    ],
    multicall: false,
    batch: false,
  },
  // OKC
  66: {
    http: [
      //   77ms
      "https://oktc.drpc.org",
      //  537ms
      "https://exchainrpc.okex.org",
    ],
    multicall: true,
    batch: true,
  },
  // EthereumPoW
  10001: {
    http: [
      //   71ms
      "https://mainnet.ethereumpow.org",
    ],
    multicall: true,
    batch: true,
  },
  // Base
  8453: {
    http: [
      //   73ms
      "https://base.drpc.org",
      //   89ms
      "https://base.rpc.sentio.xyz",
      //  136ms
      "https://developer-access-mainnet.base.org",
      //  136ms
      "https://mainnet.base.org",
      //  152ms
      "https://base-rpc.publicnode.com",
    ],
    multicall: true,
    batch: true,
  },
  // PulseChain
  369: {
    http: [
      //   63ms
      "https://rpc.pulsechainstats.com",
      //   99ms
      "https://pulsechain-rpc.publicnode.com",
      //  198ms
      "https://one.valve.city/rpc/vk_demo/evm/369",
      //  215ms
      "https://rpc-pulsechain.g4mm4.io",
      //  242ms
      "https://rpc.pulsechainrpc.com",
    ],
    multicall: true,
    batch: true,
  },
};
